name: azlistview
description: A Flutter sticky headers & index ListView. IndexBar. such as citylist, contactlist. index and hover effect.
version: 3.0.0
homepage: https://github.com/flutterchina/azlistview

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  scrollable_positioned_list:
    git:
      url: https://github.com/chunlee-thong/flutter.widgets.git
      ref: v0.4.0
      path: packages/scrollable_positioned_list

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
